site_name: PGraf Cypher
site_description: Neo4j Cypher to PostgreSQL SQL translator for graph data
site_author: Gavin M. Roy
site_url: https://gmr.github.io/pgraf-cypher/

repo_name: gmr/pgraf-cypher
repo_url: https://github.com/gmr/pgraf-cypher
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [pgraf]
          options:
            docstring_style: google
            show_root_heading: true
            show_source: true
            show_bases: true
            heading_level: 2

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
    - Database Setup: getting-started/database-setup.md
  - User Guide:
    - Basic Usage: user-guide/basic-usage.md
    - Cypher Features: user-guide/cypher-features.md
    - Advanced Queries: user-guide/advanced-queries.md
    - Error Handling: user-guide/error-handling.md
  - Examples:
    - Simple Queries: examples/simple-queries.md
    - Complex Patterns: examples/complex-patterns.md
    - Real-world Use Cases: examples/real-world.md
  - API Reference:
    - PGrafCypher: api/pgraf-cypher.md
    - Models: api/models.md
    - Parsers: api/parsers.md
    - SQL Translation: api/to-sql.md
  - Development:
    - Contributing: development/contributing.md
    - Testing: development/testing.md
    - Architecture: development/architecture.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/gmr/pgraf
      name: pgraf on GitHub
